import http from 'k6/http';

import { sleep } from 'k6';


export default function () {
    let min = -10;
    let counter = 1;
    while(counter-- > 0) {
    min += 10;
    const user = `user${__VU + min}`;
    http.get(`http://localhost:8000/transactions/create_user/${user}/`);
    http.get(`http://localhost:8000/transactions/add/${user}/63511.53/`); 
    http.get(`http://localhost:8000/transactions/quote/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/276.83/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/quote/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/add/${user}/45016.23/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    //http.get(`http://localhost:8000/transactions/display_summary/${user}/`); 
    http.get(`http://localhost:8000/transactions/add/${user}/71879.98/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/303.83/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/add/${user}/74315.15/`); 
    http.get(`http://localhost:8000/transactions/cancel_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_buy/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/commit_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/51.49/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/156.07/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/575.27/`); 
    http.get(`http://localhost:8000/transactions/cancel_sell/${user}/`); 
    //http.get(`http://localhost:8000/transactions/display_summary/${user}/`); 
    http.get(`http://localhost:8000/transactions/set_buy_amount/${user}/S/658.38/`); 
    http.get(`http://localhost:8000/transactions/sell/${user}/S/641.90/`); 
    http.get(`http://localhost:8000/transactions/commit_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_sell/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/commit_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/264.17/`); 
    http.get(`http://localhost:8000/transactions/quote/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/657.49/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    //http.get(`http://localhost:8000/transactions/display_summary/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/710.47/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/208.11/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    //http.get(`http://localhost:8000/transactions/display_summary/${user}/`); 
    http.get(`http://localhost:8000/transactions/add/${user}/52802.93/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/433.22/`); 
    http.get(`http://localhost:8000/transactions/set_sell_trigger/${user}/S/59.23/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/387.59/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_buy/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_buy/${user}/S/`); 
    //http.get(`http://localhost:8000/transactions/display_summary/${user}/`); 
    http.get(`http://localhost:8000/transactions/quote/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/quote/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/sell/${user}/S/429.74/`); 
    http.get(`http://localhost:8000/transactions/set_sell_trigger/${user}/S/51.92/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/384.67/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/357.57/`); 
    http.get(`http://localhost:8000/transactions/cancel_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/set_sell_amount/${user}/S/216.83/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_sell/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/516.29/`); 
    http.get(`http://localhost:8000/transactions/cancel_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/sell/${user}/S/41.47/`); 
    http.get(`http://localhost:8000/transactions/set_sell_trigger/${user}/S/30.04/`); 
    http.get(`http://localhost:8000/transactions/commit_sell/S/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_buy/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_sell/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/289.68/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_buy/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/add/${user}/87863.73/`); 
    http.get(`http://localhost:8000/transactions/quote/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/333.91/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/sell/${user}/S/213.24/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/427.36/`); 
    http.get(`http://localhost:8000/transactions/cancel_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/730.08/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/36.79/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/sell/${user}/S/644.65/`); 
    http.get(`http://localhost:8000/transactions/cancel_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_sell/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/cancel_sell/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_set_sell/${user}/S/`); 
    http.get(`http://localhost:8000/transactions/buy/${user}/S/749.86/`); 
    http.get(`http://localhost:8000/transactions/commit_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/cancel_buy/${user}/`); 
    http.get(`http://localhost:8000/transactions/sell/${user}/S/664.10/`); 
    //http.get(`http://localhost:8000/transactions/dumplog/./testlog`);    
    }

}