# Generated by Django 3.2.12 on 2022-04-02 05:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('server', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=24)),
                ('triggerAmount', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UncomittedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('funds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64)),
                ('funds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransactionLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.log')),
                ('actions', models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove')], max_length=6)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=24)),
            ],
            bases=('transactions.log',),
        ),
        migrations.CreateModel(
            name='ErrorEventLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.log')),
                ('command', models.CharField(choices=[('ADD', 'Add'), ('QUOTE', 'Quote'), ('BUY', 'Buy'), ('COMMIT_BUY', 'Commit Buy'), ('CANCEL_BUY', 'Cancel Buy'), ('SELL', 'Sell'), ('COMMIT_SELL', 'Commit Sell'), ('CANCEL_SELL', 'Cancel Sell'), ('SET_BUY_AMOUNT', 'Set Buy Amount'), ('CANCEL_SET_BUY', 'Cancel Set Buy'), ('SET_BUY_TRIGGER', 'Set Buy Trigger'), ('SET_SELL_AMOUNT', 'Set Sell Amount'), ('SET_SELL_TRIGGER', 'Set Sell Trigger'), ('CANCEL_SET_SELL', 'Cancel Set Sell'), ('DUMPLOG', 'Dumplog'), ('DISPLAY_SUMMARY', 'Display Summary')], max_length=16)),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('filename', models.CharField(max_length=64, null=True)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
                ('error_message', models.CharField(max_length=64, null=True)),
            ],
            bases=('transactions.log',),
        ),
        migrations.CreateModel(
            name='QuoteServerLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.log')),
                ('price', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('quoteServerTime', models.DecimalField(decimal_places=0, max_digits=24, null=True)),
                ('cryptokey', models.CharField(max_length=64, null=True)),
            ],
            bases=('transactions.log',),
        ),
        migrations.CreateModel(
            name='SetBuy',
            fields=[
                ('settransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.settransaction')),
            ],
            bases=('transactions.settransaction',),
        ),
        migrations.CreateModel(
            name='SetSell',
            fields=[
                ('settransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.settransaction')),
            ],
            bases=('transactions.settransaction',),
        ),
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.log')),
                ('command', models.CharField(choices=[('ADD', 'Add'), ('QUOTE', 'Quote'), ('BUY', 'Buy'), ('COMMIT_BUY', 'Commit Buy'), ('CANCEL_BUY', 'Cancel Buy'), ('SELL', 'Sell'), ('COMMIT_SELL', 'Commit Sell'), ('CANCEL_SELL', 'Cancel Sell'), ('SET_BUY_AMOUNT', 'Set Buy Amount'), ('CANCEL_SET_BUY', 'Cancel Set Buy'), ('SET_BUY_TRIGGER', 'Set Buy Trigger'), ('SET_SELL_AMOUNT', 'Set Sell Amount'), ('SET_SELL_TRIGGER', 'Set Sell Trigger'), ('CANCEL_SET_SELL', 'Cancel Set Sell'), ('DUMPLOG', 'Dumplog'), ('DISPLAY_SUMMARY', 'Display Summary')], max_length=16)),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('filename', models.CharField(max_length=64, null=True)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=24)),
            ],
            bases=('transactions.log',),
        ),
        migrations.CreateModel(
            name='UncommittedBuy',
            fields=[
                ('uncomittedtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.uncomittedtransaction')),
            ],
            bases=('transactions.uncomittedtransaction',),
        ),
        migrations.CreateModel(
            name='UncommittedSell',
            fields=[
                ('uncomittedtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.uncomittedtransaction')),
            ],
            bases=('transactions.uncomittedtransaction',),
        ),
        migrations.CreateModel(
            name='UserCommandLog',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.log')),
                ('command', models.CharField(choices=[('ADD', 'Add'), ('QUOTE', 'Quote'), ('BUY', 'Buy'), ('COMMIT_BUY', 'Commit Buy'), ('CANCEL_BUY', 'Cancel Buy'), ('SELL', 'Sell'), ('COMMIT_SELL', 'Commit Sell'), ('CANCEL_SELL', 'Cancel Sell'), ('SET_BUY_AMOUNT', 'Set Buy Amount'), ('CANCEL_SET_BUY', 'Cancel Set Buy'), ('SET_BUY_TRIGGER', 'Set Buy Trigger'), ('SET_SELL_AMOUNT', 'Set Sell Amount'), ('SET_SELL_TRIGGER', 'Set Sell Trigger'), ('CANCEL_SET_SELL', 'Cancel Set Sell'), ('DUMPLOG', 'Dumplog'), ('DISPLAY_SUMMARY', 'Display Summary')], max_length=16)),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('filename', models.CharField(max_length=64, null=True)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
            ],
            bases=('transactions.log',),
        ),
        migrations.AddField(
            model_name='uncomittedtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.user'),
        ),
        migrations.CreateModel(
            name='StockAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=3)),
                ('funds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.user')),
            ],
        ),
        migrations.AddField(
            model_name='settransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.user'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.user'),
        ),
    ]
