# Generated by Django 3.2.12 on 2022-03-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=32)),
                ('cumulative_funds', models.DecimalField(decimal_places=2, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(max_length=64)),
                ('command', models.CharField(choices=[('ADD', 'Add'), ('QUOTE', 'Quote'), ('BUY', 'Buy'), ('COMMIT_BUY', 'Commit Buy'), ('CANCEL_BUY', 'Cancel Buy'), ('SELL', 'Sell'), ('COMMIT_SELL', 'Commit Sell'), ('CANCEL_SELL', 'Cancel Sell'), ('SET_BUY_AMOUNT', 'Set Buy Amount'), ('CANCEL_SET_BUY', 'Cancel Set Buy'), ('SET_BUY_TRIGGER', 'Set Buy Trigger'), ('SET_SELL_AMOUNT', 'Set Sell Amount'), ('SET_SELL_TRIGGER', 'Set Sell Trigger'), ('CANCEL_SET_SELL', 'Cancel Set Sell'), ('DUMPLOG', 'Dumplog'), ('DISPLAY_SUMMARY', 'Display Summary')], max_length=16)),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24, null=True)),
                ('filename', models.CharField(max_length=64, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SYSTEM', 'System'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], max_length=6)),
                ('event_source', models.CharField(choices=[('USER_COMMAND', 'User Command'), ('INTERSERVER_COMMUNICATION', 'Interserver Communiation'), ('TRIGGER_EXECUTION', 'Trigger Execution')], max_length=25)),
                ('message', models.CharField(max_length=512, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transactions.transaction')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(max_length=64)),
                ('actions', models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove')], max_length=6)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
        ),
    ]
