# Generated by Django 3.2.12 on 2022-03-03 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(max_length=64)),
                ('command', models.CharField(choices=[('ADD', 'Add'), ('QUOTE', 'Quote'), ('BUY', 'Buy'), ('COMMIT_BUY', 'Commit Buy'), ('CANCEL_BUY', 'Cancel Buy'), ('SELL', 'Sell'), ('COMMIT_SELL', 'Commit Sell'), ('CANCEL_SELL', 'Cancel Sell'), ('SET_BUY_AMOUNT', 'Set Buy Amount'), ('CANCEL_SET_BUY', 'Cancel Set Buy'), ('SET_BUY_TRIGGER', 'Set Buy Trigger'), ('SET_SELL_AMOUNT', 'Set Sell Amount'), ('SET_SELL_TRIGGER', 'Set Sell Trigger'), ('CANCEL_SET_SELL', 'Cancel Set Sell'), ('DUMPLOG', 'Dumplog'), ('DISPLAY_SUMMARY', 'Display Summary')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=32)),
                ('cumulative_funds', models.DecimalField(decimal_places=2, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=512)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='DebugEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_message', models.CharField(max_length=512)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='SetSellTriggerCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='SetSellAmountCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='SetBuyTriggerCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='SetBuyAmountCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='SellCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='QuoteCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='DumplogCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('filename', models.CharField(max_length=64, null=True)),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='DisplaySummaryCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='CommitSellCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='CommitBuyCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='CancelSetSellCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='CancelSetBuyCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='CancelSellCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='CancelBuyCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='BuyCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('stock_symbol', models.CharField(max_length=3, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='AddCommand',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transactions.transaction')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(max_length=64)),
                ('actions', models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove')], max_length=6)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.useraccount')),
            ],
        ),
    ]
