# Generated by Django 3.2.12 on 2022-03-03 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220303_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='UncommittedBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=50)),
                ('funds', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.user')),
            ],
        ),
    ]
