# Generated by Django 3.2.12 on 2022-03-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quoteServerTime',
            field=models.DecimalField(decimal_places=0, max_digits=24, null=True),
        ),
    ]
