version: "3.9"

# This file was taken from Docker's sample applications documentation. See:
# https://docs.docker.com/samples/django/

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUOTE_SERVER_HOST=192.168.4.2
      - QUOTE_SERVER_PORT=4444
    depends_on:
      - database
      - redis # NEW
  redis:
    image: redis:alpine
  
  celery:
    build: .
    command: celery -A transaction_server worker -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - QUOTE_SERVER_HOST=192.168.4.2
      - QUOTE_SERVER_PORT=4444
    depends_on:
      - redis
  
  celery-beat:
    build: .
    command: celery -A transaction_server beat -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - QUOTE_SERVER_HOST=192.168.4.2
      - QUOTE_SERVER_PORT=4444
    depends_on:
      - redis